### ISSUE TITLE
Problem feeds

### ISSUE THREAD

**Issue by alekorn102** [andreyglauzer/VulnAlert#1]
Very good work! but I can't get it to work!
When I launch the script like this, 

`./VulnAlert.py -i -c utils/config/config.yml -t Telegram`

```
Traceback (most recent call last):
  File "./VulnAlert.py", line 512, in <module>
    alerts.start
  File "./VulnAlert.py", line 412, in start
    self.download()
  File "./VulnAlert.py", line 494, in download
    loaded = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```
Could you help me please?What am I doing wrong?

I have the python version 3.5.3

Thank you!

**Comment by andreyglauzer** [comment]
Hello thank you so much.

Is there a debug mode in the script, can you use it, and put the output here?

By the error it seems that it was not possible to download the NDV lists, you can check if it is possible to download this file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2016.json.zip

**Comment by alekorn102** [comment]
try wget and download the file ok.
change the debug value to TRUE but not change at all.
![image](https://user-images.githubusercontent.com/35205097/83929177-da5a2680-a768-11ea-928d-7df2f00687e1.png)

when I query the databases.db I get no result. you're probably not downloading the file

![image](https://user-images.githubusercontent.com/35205097/83929928-90bf0b00-a76b-11ea-8878-e0d3dfa81307.png)


Thanks for your time!!

**Comment by alekorn102** [comment]
already solved! environment configuration problem.
Thank you very much. If I only wanted you to send me the latest CVE, should I just download this? "https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.zip",
in principle I am only interested in knowing the vulnerabilities that come out the same day. And then configure a daily CRON to send me the messages with the information.
Again, thanks so much for the Script!

**Comment by andreyglauzer** [comment]
Hello, I'm sorry for the delay

What a great solution, if you can share what you did here.

To get the most recent ones, always use the current year's feed together with recent.
